spring:
  application:
    name: customer
  data:
    mongodb:
      password: abc123
      username: myUserAdmin
      host: localhost
      port: 27017
#      database: GraphQL
      database: Customer
server:
  port: 9090
graphql:
  servlet:
    mapping: /graphql